export const places = [
  {
    id: 1,
    title: "Chiang Mai",
    location: "Thailand",
    description:
      "Chiang Mai is a land of misty mountains and colourful hill tribes, a playground for seasoned travellers, a paradise for shoppers and a delight for adventurers.",
    imageUrl:
      "https://images.pexels.com/photos/5709844/pexels-photo-5709844.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    price: 50,
    rating: 4.5,
    image: [
      "https://images.pexels.com/photos/3225517/pexels-photo-3225517.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/15286/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/3225518/pexels-photo-3225518.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/3415629/pexels-photo-3415629.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/4111720/pexels-photo-4111720.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    category: "City",
    featured: true,
    amenities: ["Free wifi", "Breakfast included", "Gym", "Swimming pool"],
    host: {
      name: "John Doe",
      avatarUrl: "https://picsum.photos/id/237/200/200",
      isSuperhost: true,
    },
  },
  {
    id: 2,
    title: "Cusco",
    location: "Peru",
    description:
      "Cusco is a city in southeastern Peru near the Urubamba Valley of the Andes mountain range. It is the capital of the Cusco Region and of the Cusco Province.",
    imageUrl: "https://picsum.photos/id/1018/500/300",
    price: 40,
    rating: 4.0,
    category: "mountain",
    featured: false,
    amenities: ["Free wifi", "Breakfast included", "Airport shuttle"],
    host: {
      name: "Jane Doe",
      avatarUrl: "https://picsum.photos/id/238/200/200",
      isSuperhost: false,
    },
  },
  {
    id: 3,
    title: "Machu Picchu",
    location: "Peru",
    description:
      "Machu Picchu is a 15th-century Inca citadel situated on a mountain ridge 2,430 metres above sea level. It is located in the Cusco Region, Urubamba Province, Machupicchu District in Peru.",
    imageUrl: "https://picsum.photos/id/1015/500/300",
    price: 60,
    rating: 4.8,
    category: "Beach",
    featured: true,
    amenities: ["Free wifi", "Breakfast included", "Private bathroom"],
    host: {
      name: "Jack Smith",
      avatarUrl: "https://picsum.photos/id/239/200/200",
      isSuperhost: true,
    },
  },
  {
    id: 4,
    title: "Kyoto",
    location: "Japan",
    description:
      "Kyoto is a city located in the central part of the island of Honshu, Japan. It has a population close to 1.5 million.",
    imageUrl: "https://picsum.photos/id/1019/500/300",
    price: 55,
    rating: 4,
    category: "Historical",
    featured: false,
    amenities: ["Free wifi", "Breakfast included", "Gym"],
    host: {
      name: "Jill Smith",
      avatarUrl: "https://picsum.photos/id/240/200/200",
      isSuperhost: false,
    },
  },
  {
    id: 5,
    title: "Goa",
    location: "India",
    description:
      "Kyoto is a city located in the central part of the island of Honshu, Japan. It has a population close to 1.5 million.",
    imageUrl: "https://picsum.photos/id/1037/500/300",
    price: 55,
    rating: 4,
    category: "mountain",
    featured: false,
    amenities: ["Free wifi", "Breakfast included", "Gym"],
    host: {
      name: "Jill Smith",
      avatarUrl: "https://picsum.photos/id/240/200/200",
      isSuperhost: false,
    },
  },
  {
    id: 6,
    title: "Bejeing",
    location: "China",
    description:
      "Kyoto is a city located in the central part of the island of Honshu, Japan. It has a population close to 1.5 million.",
    imageUrl: "https://picsum.photos/id/1035/500/300",
    price: 55,
    rating: 4,
    category: "Historical",
    featured: false,
    amenities: ["Free wifi", "Breakfast included", "Gym"],
    host: {
      name: "Jill Smith",
      avatarUrl: "https://picsum.photos/id/240/200/200",
      isSuperhost: false,
    },
  },
  {
    id: 7,
    title: "Toronto",
    location: "Canada",
    description:
      "Kyoto is a city located in the central part of the island of Honshu, Japan. It has a population close to 1.5 million.",
    imageUrl: "https://picsum.photos/id/1036/500/300",
    price: 55,
    rating: 4,
    category: "City",
    featured: false,
    amenities: ["Free wifi", "Breakfast included", "Gym"],
    host: {
      name: "Jill Smith",
      avatarUrl: "https://picsum.photos/id/240/200/200",
      isSuperhost: false,
    },
  },
  {
    id: 8,
    title: "pokhra",
    location: "Nepal",
    description:
      "Kyoto is a city located in the central part of the island of Honshu, Japan. It has a population close to 1.5 million.",
    imageUrl: "https://picsum.photos/id/1029/500/300",
    price: 55,
    rating: 4,
    category: "City",
    featured: false,
    amenities: ["Free wifi", "Breakfast included", "Gym"],
    host: {
      name: "Jill Smith",
      avatarUrl: "https://picsum.photos/id/240/200/200",
      isSuperhost: false,
    },
  },
];
